"""First migration

Revision ID: 6b8f29f10552
Revises: 
Create Date: 2026-07-26 19:41:53.961241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b8f29f10552'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downloaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column("filename", sa.String(), nullable=False),
    sa.Column("file_path", sa.String(), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_downloaded_files_filename'), 'downloaded_files', ['filename'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloaded_files_filename'), table_name='downloaded_files')
    op.drop_table('downloaded_files')
    # ### end Alembic commands ###
